#!/usr/bin/env node
/**
 * WHAT: Exercises source fingerprints, provenance chains, and signed seal verification.
 * WHY: Integrity claims need proof that stable input passes while edited history and forged signatures fail.
 * HOW: Creates temporary fixtures, computes seals, mutates evidence, and checks every result with assertions.
 * INPUTS: Temporary files and deterministic in-memory provenance events generated by this script.
 * OUTPUTS: A passed-group count on standard output, or an assertion failure and nonzero exit.
 * CALLERS: Developers and provenance test gates run this executable directly.
 * @example node tools/lib/provenance-seal-selftest.ts
 */
/**
 * Self-test for provenance seals. Proves: fingerprints are deterministic and
 * line-ending-stable, the seal chain detects edited history, and ed25519
 * signing detects a forger who recomputes the chain.
 * Run: node tools/lib/provenance-seal-selftest.ts
 */
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import {
  fingerprintSource, computeSeal, verifySeal, canonicalEvent,
  generateSealKeypair, signSealHead, verifySealSignature,
} from './provenance-seal.ts';

let n = 0;
const dir = mkdtempSync(resolve(tmpdir(), 'seal-selftest-'));
try {
  // --- fingerprint determinism + line-ending stability ---
  writeFileSync(resolve(dir, 'a.js'), 'export const x = 1;\nexport const y = 2;\n');
  writeFileSync(resolve(dir, 'b.ts'), 'const z = 3;\n');
  const fp1 = fingerprintSource(dir);
  const fp2 = fingerprintSource(dir);
  assert.equal(fp1.content_hash, fp2.content_hash, 'fingerprint must be deterministic');
  assert.equal(fp1.file_count, 2);
  n += 1;

  // CRLF variant hashes the same (normalized)
  writeFileSync(resolve(dir, 'a.js'), 'export const x = 1;\r\nexport const y = 2;\r\n');
  const fpCRLF = fingerprintSource(dir);
  assert.equal(fpCRLF.content_hash, fp1.content_hash, 'CRLF vs LF must not change identity');
  n += 1;

  // real content change flips the hash
  writeFileSync(resolve(dir, 'a.js'), 'export const x = 999;\n');
  const fpChanged = fingerprintSource(dir);
  assert.notEqual(fpChanged.content_hash, fp1.content_hash, 'content change must change identity');
  n += 1;

  // --- seal chain detects edited history ---
  const events = [
    { actor_kind: 'human', actor_id: 'alice@x.com', role: 'architect', timestamp: '2026-01-01T00:00:00Z', commit: 'aaa', summary: 'created' },
    { actor_kind: 'human', actor_id: 'bob@x.com', role: 'implementer', timestamp: '2026-01-02T00:00:00Z', commit: 'bbb', summary: 'edit' },
  ];
  const seal = computeSeal({ brick_id: 'brick-1', content_hash: fp1.content_hash, events });
  assert.equal(verifySeal(seal, { brick_id: 'brick-1', content_hash: fp1.content_hash, events }).ok, true);
  n += 1;

  // forge: remove the original author
  const forged = [{ ...events[1], actor_id: 'attacker@evil.com' }];
  const v = verifySeal(seal, { brick_id: 'brick-1', content_hash: fp1.content_hash, events: forged });
  assert.equal(v.ok, false, 'edited history must break the seal');
  assert.ok(v.reasons.some((r) => r.includes('head mismatch')));
  n += 1;

  // source drift breaks the anchor
  const drifted = verifySeal(seal, { brick_id: 'brick-1', content_hash: fpChanged.content_hash, events });
  assert.equal(drifted.ok, false, 'source drift must break the anchor');
  assert.ok(drifted.reasons.some((r) => r.includes('anchor mismatch')));
  n += 1;

  // --- ed25519 signing detects the recompute forger ---
  const { publicPem, privatePem } = generateSealKeypair();
  const sig = signSealHead(seal.head, privatePem);
  assert.equal(verifySealSignature(seal.head, sig, publicPem), true, 'valid signature must verify');
  n += 1;

  // a forger recomputes a consistent chain head for the forged events...
  const forgedSeal = computeSeal({ brick_id: 'brick-1', content_hash: fp1.content_hash, events: forged });
  // ...but cannot produce a signature over the new head without the private key.
  assert.equal(verifySealSignature(forgedSeal.head, sig, publicPem), false,
    'signature over the original head must NOT validate the forged head');
  n += 1;

  // canonicalEvent is stable and ignores non-chained fields
  assert.equal(
    canonicalEvent({ ...events[0], summary: '  created  ' }),
    canonicalEvent(events[0]),
    'summary whitespace should not change the canonical form',
  );
  n += 1;

  console.log(`provenance-seal selftest: ${String(n)} assertions passed`);
} finally {
  rmSync(dir, { recursive: true, force: true });
}
