import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { cp, mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import { dispatch } from "../lib/workforce/contract.mjs";
import { runWorkforceProcess } from "../lib/workforce/process-runner.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

test("schema declaration generator detects missing and stale outputs, then repairs them deterministically", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "smarch-schema-generator-"));
  try {
    const generatorDir = path.join(root, "tools", "lib", "schema-types");
    await mkdir(generatorDir, { recursive: true });
    await cp(path.join(repoRoot, "schemas"), path.join(root, "schemas"), { recursive: true });
    await cp(path.join(repoRoot, "tools", "lib", "schema-types", "generate.mjs"), path.join(generatorDir, "generate.mjs"));
    const generator = path.join(generatorDir, "generate.mjs");
    await writeFile(path.join(root, "schemas", "coverage-shared.schema.json"), JSON.stringify({
      type: "object",
      $defs: {
        Payload: {
          type: "object",
          required: ["status"],
          properties: { status: { $ref: "#/$defs/Status" } },
        },
        Status: { enum: ["zeta", "alpha"] },
      },
    }));
    await writeFile(path.join(root, "schemas", "coverage-root.schema.json"), JSON.stringify({
      type: "object",
      required: ["mode", "payload", "step"],
      properties: {
        mode: { enum: ["beta", "alpha"] },
        payload: { $ref: "coverage-shared.schema.json#/$defs/Payload" },
        step: { $ref: "#/$defs/StepOne" },
      },
      $defs: {
        StepOne: { $ref: "#/$defs/StepTwo" },
        StepTwo: { enum: ["second", "first"] },
      },
    }));

    const missing = spawnSync(process.execPath, [generator, "--check"], { encoding: "utf8" });
    assert.equal(missing.status, 1);
    assert.match(missing.stderr, /schema type declarations are stale/);

    const generated = spawnSync(process.execPath, [generator], { encoding: "utf8" });
    assert.equal(generated.status, 0, generated.stderr);
    assert.match(generated.stdout, /generated \d+ schema type declarations/);
    const indexPath = path.join(generatorDir, "index.d.ts");
    const original = await readFile(indexPath, "utf8");
    assert.match(original, /Generated by tools\/lib\/schema-types\/generate\.mjs/);
    assert.match(original, /export \* from/);
    const edgeShapes = await readFile(path.join(generatorDir, "coverage-root.schema.d.ts"), "utf8");
    assert.match(edgeShapes, /import type \{ CoverageSharedPayload \} from "\.\/coverage-shared\.schema\.js";/);
    assert.match(edgeShapes, /export type CoverageRootStepOne = CoverageRootStepTwo;/);
    assert.match(edgeShapes, /export type CoverageRootStepTwo = "first" \| "second";/);
    assert.match(edgeShapes, /mode: "alpha" \| "beta";/);
    assert.match(edgeShapes, /payload: CoverageSharedPayload;/);
    assert.match(edgeShapes, /step: CoverageRootStepOne;/);

    const current = spawnSync(process.execPath, [generator, "--check"], { encoding: "utf8" });
    assert.equal(current.status, 0, current.stderr);
    assert.match(current.stdout, /declarations are current/);

    await writeFile(indexPath, `${original}// drift\n`);
    const stale = spawnSync(process.execPath, [generator, "--check"], { encoding: "utf8" });
    assert.equal(stale.status, 1);
    assert.match(stale.stderr, /index\.d\.ts/);

    assert.equal(spawnSync(process.execPath, [generator], { encoding: "utf8" }).status, 0);
    assert.equal(await readFile(indexPath, "utf8"), original);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("workforce contract validates packets, normalizes failures, retries only retryable results, and forwards options", async () => {
  process.env.SMA_WORKFORCE_NO_USAGE_LOG = "1";
  assert.equal((await dispatch(null)).raw.error, "workforce packet is required");
  assert.equal((await dispatch("x", { timeoutMs: 0 })).raw.error, "timeoutMs must be a positive number");
  assert.match(String((await dispatch("x", { backend: "missing-backend", timeoutMs: 50 })).raw.error), /unknown workforce backend/);

  /** @type {Array<{ packet: unknown, options: Record<string, unknown> }>} */
  const received = [];
  let attempts = 0;
  const result = await dispatch({ task: "prove" }, {
    backend: { async execute(/** @type {unknown} */ packet, /** @type {Record<string, unknown>} */ options) {
      attempts += 1;
      received.push({ packet, options });
      if (attempts === 1) return { ok: false, retryable: true, raw: { error: "transient" } };
      return { ok: true, output: "done", tokensIn: 9, tokensOut: 4, raw: { backend: "fixture" } };
    } },
    model: "fixture-model",
    effort: "xhigh",
    schema: "fixture-schema",
    readOnly: true,
    cwd: "/tmp/fixture",
    timeoutMs: 2_000,
  });
  assert.equal(attempts, 2);
  assert.deepEqual(result, { ok: true, output: "done", tokensIn: 9, tokensOut: 4, raw: { backend: "fixture" } });
  assert.deepEqual(received[1].packet, { task: "prove" });
  assert.equal(received[1].options.model, "fixture-model");
  assert.equal(received[1].options.effort, "xhigh");
  assert.equal(received[1].options.schema, "fixture-schema");
  assert.equal(received[1].options.readOnly, true);
  assert.equal(received[1].options.cwd, "/tmp/fixture");
  assert.ok(received[1].options.signal instanceof AbortSignal);

  let terminalAttempts = 0;
  const terminal = await dispatch("x", { backend: async () => {
    terminalAttempts += 1;
    return { ok: false, retryable: false, output: 0, tokensIn: Number.NaN, tokensOut: Infinity };
  }, timeoutMs: 100 });
  assert.equal(terminalAttempts, 1);
  assert.equal(terminal.ok, false);
  assert.equal(terminal.output, 0);
  assert.equal(terminal.tokensIn, 0);
  assert.equal(terminal.tokensOut, 0);

  const invalid = await dispatch("x", { backend: /** @type {any} */ (async () => "invalid"), timeoutMs: 2_000 });
  assert.equal(invalid.ok, false);
  assert.match(String(invalid.raw.error), /invalid result/);

  const timedOut = await dispatch("slow", { backend: { execute: () => new Promise(() => {}) }, timeoutMs: 15 });
  assert.equal(timedOut.ok, false);
  assert.equal(timedOut.raw.timedOut, true);
  assert.match(String(timedOut.raw.error), /timed out after 15ms/);
});

test("workforce explicit backend wins over environment and thrown attempts exhaust the retry contract", async () => {
  const previousBackend = process.env.SMA_WORKFORCE_BACKEND;
  process.env.SMA_WORKFORCE_BACKEND = "environment-backend-must-not-load";
  try {
    let explicitCalls = 0;
    const explicit = await dispatch("precedence", {
      backend: async (/** @type {unknown} */ _packet, /** @type {Record<string, unknown>} */ options) => {
        explicitCalls += 1;
        return { ok: true, output: options.model, raw: { backend: "explicit-fixture" } };
      },
      model: "explicit-model",
      timeoutMs: 1_000,
    });
    assert.equal(explicitCalls, 1);
    assert.equal(explicit.ok, true);
    assert.equal(explicit.output, "explicit-model");
    assert.equal(explicit.raw.backend, "explicit-fixture");

    let thrownAttempts = 0;
    const exhausted = await dispatch("retry-errors", {
      backend: async () => {
        thrownAttempts += 1;
        throw new TypeError(`attempt-${thrownAttempts}`);
      },
      timeoutMs: 2_000,
    });
    assert.equal(thrownAttempts, 3);
    assert.equal(exhausted.ok, false);
    assert.equal(exhausted.raw.name, "TypeError");
    assert.equal(exhausted.raw.error, "attempt-3");
  } finally {
    if (previousBackend === undefined) delete process.env.SMA_WORKFORCE_BACKEND;
    else process.env.SMA_WORKFORCE_BACKEND = previousBackend;
  }
});

test("workforce process runner captures streams, stdin, exit failures, and timeouts consistently", async () => {
  const echo = await runWorkforceProcess(process.execPath, ["-e", "process.stdin.pipe(process.stdout); console.error('fixture-error')"], "fixture-input", { timeoutMs: 1_000 });
  assert.equal(echo.code, 0);
  assert.equal(echo.stdout, "fixture-input");
  assert.match(echo.stderr, /fixture-error/);
  assert.equal(echo.timedOut, false);

  const failure = await runWorkforceProcess(process.execPath, ["-e", "process.exit(7)"], undefined, { timeoutMs: 1_000 });
  assert.equal(failure.code, 7);
  assert.equal(failure.timedOut, false);

  const timedOut = await runWorkforceProcess(process.execPath, ["-e", "setInterval(() => {}, 1000)"], undefined, { timeoutMs: 15 });
  assert.equal(timedOut.timedOut, true);
  assert.notEqual(timedOut.code, 0);
});
