// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export type ActiveLeasesLease = ({
  acquired_at: string;
  actor_kind?: "agent" | "ai_model" | "automation" | "human" | "tool";
  agent_id: string;
  expires_at: string;
  force_acquired_from?: string;
  force_acquired_reason?: string;
  intent: string;
  lease_id: string;
  linked_backlog?: Array<string>;
  model?: string;
  project?: string;
  rationale?: string;
  renewals?: number;
  renewed_at?: string;
  resource_id: string;
  resource_kind: "backlog" | "brick" | "build" | "import-lock" | "other" | "registry-regen" | "release" | "state-regen" | "wiki-regen";
  session_id?: string;
  task_id?: string;
});

export type ActiveLeases = {
  generated_at: string;
  leases: Array<ActiveLeasesLease>;
  schema_version: "1.0.0";
};
