// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface AgentContextEvent {
  actor_id: string;
  actor_kind: "agent" | "ai_model" | "automation" | "human" | "tool";
  brick_id: string;
  commit?: string;
  decision_rationale?: string;
  event_id: string;
  files_touched?: string[];
  gain_percent?: number;
  intent: string;
  kind: "alternative_rejected" | "conflict_detected" | "conflict_resolved" | "decision_recorded" | "edit_applied" | "edit_planned" | "lease_acquired" | "lease_expired" | "lease_force_acquired" | "lease_released" | "lease_renewed" | "merge_proposed" | "merge_resolved" | "note" | "promotion_attempted" | "promotion_blocked" | "proof_recorded" | "release_cut" | "verification_run";
  lease_id?: string;
  linked_backlog?: string[];
  model?: string;
  project?: string;
  proof?: string[];
  rejected_alternatives?: {
    alternative: string;
    reason: string;
  }[];
  schema_version: "1.0.0";
  session_id?: string;
  task_id?: string;
  timestamp: string;
  verification?: ({
    command?: string;
    notes?: string;
    output_path?: string;
    status?: "blocked" | "fail" | "pass" | "skipped";
  });
}
