// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface Backlog {
  entries: ({
    blocks_promotion_to?: (("candidate" | "canonical" | "publishable" | "verified")[]);
    closed_at?: string;
    closed_by?: string;
    description?: string;
    estimated_effort_hours?: number;
    estimated_token_cost?: number;
    id: string;
    kind: "accessibility" | "boundary_violation" | "dependency_drift" | "documentation" | "duplicate_brick" | "env_undeclared" | "manifest_drift" | "missing_types" | "naming" | "other" | "performance" | "platform_coupling" | "rls_missing" | "supply_chain" | "test_missing" | "typecheck_disabled";
    linked_to?: {
      github_issue?: string;
      linear_id?: string;
      reuse_receipt_id?: string;
    };
    opened_at: string;
    opened_by?: string;
    resolution?: string;
    scope: {
      brick_id?: string;
      files?: string[];
      package?: string;
    };
    severity: "blocker" | "high" | "low" | "medium" | "nit";
    status: "blocked" | "in_progress" | "open" | "resolved" | "wontfix";
    title: string;
  }[]);
  generated_at: string;
  project: string;
  schema_version: "1.0.0";
}
