// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface BrickManifestEnvVar {
  example?: string;
  forbidden_in?: (("ci" | "client_bundle" | "docs" | "logs" | "tests")[]);
  name: string;
  required_in: (("ci" | "local" | "preview" | "production" | "test")[]);
  scope: "ci_only" | "local_only" | "public_client" | "server_only";
}

export interface BrickManifestGateScore {
  evidence?: string[];
  notes?: string;
  score: number;
  status: "blocked" | "missing" | "not_applicable" | "partial" | "passing";
}

export interface BrickManifestProvenanceSeal {
  algo: string;
  anchor?: string;
  chain_length?: number;
  events_digest?: string;
  head: string;
  key_id?: string;
  signature?: string;
}

export interface BrickManifestTouchEvent {
  actor_id: string;
  actor_kind: "agent" | "ai_model" | "automation" | "human" | "tool";
  attestation?: ({
    hash?: string;
    method?: "agent_runner" | "ci_job" | "git_commit" | "manual" | "scanner";
    reference?: string;
  });
  commit?: string;
  context_event_ids?: string[];
  decision_rationale?: string;
  files_touched?: string[];
  intent?: string;
  lease_id?: string;
  linked_backlog?: string[];
  model?: string;
  provider?: string;
  rejected_alternatives?: {
    alternative: string;
    reason: string;
  }[];
  role: "architect" | "implementer" | "refactor" | "release" | "reviewer" | "scanner" | "security" | "tester";
  session_id?: string;
  summary: string;
  task_id?: string;
  timestamp: string;
  verification?: BrickManifestVerificationEvent[];
}

export interface BrickManifestVerificationEvent {
  command: string;
  notes?: string;
  output_path?: string;
  status: "blocked" | "fail" | "pass" | "passing" | "skipped";
  timestamp?: string;
}

export interface BrickManifest {
  boundaries: {
    allowed_side_effects?: string[];
    forbidden_imports?: string[];
    owned_paths: string[];
    private_paths: string[];
    public_paths: string[];
  };
  brick: ({
    domain?: string[];
    frameworks?: string[];
    id: string;
    kind: "adapter" | "capsule" | "guard" | "module_group" | "module" | "submodule" | "template" | "tooling";
    language: string[];
    name: string;
    registry_origin?: string;
    replication?: ({
      auto_pr_on_minor?: boolean;
      auto_pr_on_patch?: boolean;
      deprecation_window_days?: number;
      notify_owners?: string[];
      policy?: "fork-snapshot" | "manual" | "pin-version" | "track-canonical";
    });
    status: "candidate" | "canonical" | "duplicate" | "experimental" | "legacy" | "project_bound" | "variant";
    version: string;
  });
  classification: ({
    data_classes: (("admin_only" | "credential" | "health_sensitive" | "org_private" | "payment" | "pii" | "public" | "regulated" | "user_private")[]);
    notes?: string;
    risk: "critical" | "high" | "low" | "medium";
  });
  clone: ({
    adaptation_points: string[];
    install_steps: string[];
    known_traps: string[];
    readiness: "blocked" | "copy_ready" | "guided" | "manual_only";
  });
  hierarchy?: ({
    component_policy?: "internal_by_default" | "manifest_required" | "public_component_brick";
    contains?: (("adapter" | "brick" | "component" | "file" | "hook" | "module" | "service" | "submodule" | "utility")[]);
    group_id?: string;
    level: "brick_group" | "brick" | "component" | "module" | "submodule";
    notes?: string;
    parent_brick_id?: string;
    parent_module_id?: string;
  });
  interfaces: {
    adapters?: string[];
    forbidden_dependencies?: string[];
    ports?: string[];
    public_api?: string[];
    required_dependencies?: string[];
  };
  license?: ({
    attribution_required?: boolean;
    commercial_use?: boolean;
    inherited_from?: string;
    notes?: string;
    openness: "closed" | "open" | "source-available";
    redistribute?: "allowed" | "forbidden" | "with-attribution";
    spdx: string;
    visibility?: "community" | "internal" | "private" | "public";
  });
  owner: {
    primary: string;
    reviewers?: string[];
    team?: string;
  };
  provenance: ({
    created_by: BrickManifestTouchEvent;
    reviewed_by: BrickManifestTouchEvent[];
    seal?: BrickManifestProvenanceSeal;
    source_chain: ({
      brick_id: string;
      commit?: string;
      event?: "copied" | "created" | "forked" | "merged" | "promoted";
      path?: string;
      project: string;
      timestamp?: string;
    }[]);
    touched_by: BrickManifestTouchEvent[];
  });
  quality: ({
    code_budget: ({
      dependency_count: number;
      estimate_method?: string;
      exceptions?: string[];
      feature_lines: number;
      file_count: number;
      last_estimated_at?: string;
      notes?: string;
      realistic_regenerate_tokens_estimate?: number;
      static_tokens_estimate?: number;
      status: "acceptable" | "bloated" | "lean" | "unknown";
    });
    line_count: {
      max_file_lines: number;
      over_600_count: number;
    };
    score: number;
    test_commands: string[];
    verification: BrickManifestVerificationEvent[];
  });
  schema_version: "1.0.0";
  security: ({
    env: ({
      required: boolean;
      status: "complete" | "missing" | "not_applicable" | "partial";
      variables: BrickManifestEnvVar[];
    });
    rls: ({
      matrix_path?: string;
      negative_tests?: string[];
      required: boolean;
      status: "complete" | "missing" | "not_applicable" | "partial";
    });
    vulnerability_findings: {
      critical: number;
      high: number;
      low: number;
      medium: number;
      report_paths?: string[];
    };
  });
  source: {
    archive_hash?: string;
    commit?: string;
    copied_from?: {
      brick_id: string;
      commit?: string;
      copied_at?: string;
      path?: string;
      project: string;
    }[];
    paths: string[];
    project: string;
    repository?: string;
  };
  supply_chain: ({
    checksums: {
      path: string;
      sha256: string;
    }[];
    dependencies: ({
      license?: string;
      name: string;
      purpose: string;
      risk?: "high" | "low" | "medium" | "unknown";
      version?: string;
    }[]);
    licenses: string[];
    sbom_path?: string;
  });
  sweetspot: {
    sai: BrickManifestGateScore;
    sas: BrickManifestGateScore;
    sev: BrickManifestGateScore;
    spe: BrickManifestGateScore;
    srls: BrickManifestGateScore;
    srs: BrickManifestGateScore;
    ssa_v2: BrickManifestGateScore;
    ssc: BrickManifestGateScore;
    ssi: BrickManifestGateScore;
    ssra: BrickManifestGateScore;
    sstf: BrickManifestGateScore;
    sva: BrickManifestGateScore;
  };
}
