// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export type BrickManifestEnvVar = ({
  example?: string;
  forbidden_in?: (Array<"ci" | "client_bundle" | "docs" | "logs" | "tests">);
  name: string;
  required_in: (Array<"ci" | "local" | "preview" | "production" | "test">);
  scope: "ci_only" | "local_only" | "public_client" | "server_only";
});

export type BrickManifestGateScore = ({
  evidence?: Array<string>;
  notes?: string;
  score: number;
  status: "blocked" | "missing" | "not_applicable" | "partial" | "passing";
});

export type BrickManifestProvenanceSeal = {
  algo: string;
  anchor?: string;
  chain_length?: number;
  events_digest?: string;
  head: string;
  key_id?: string;
  signature?: string;
};

export type BrickManifestTouchEvent = ({
  actor_id: string;
  actor_kind: "agent" | "ai_model" | "automation" | "human" | "tool";
  attestation?: ({
    hash?: string;
    method?: "agent_runner" | "ci_job" | "git_commit" | "manual" | "scanner";
    reference?: string;
  });
  commit?: string;
  context_event_ids?: Array<string>;
  decision_rationale?: string;
  files_touched?: Array<string>;
  intent?: string;
  lease_id?: string;
  linked_backlog?: Array<string>;
  model?: string;
  provider?: string;
  rejected_alternatives?: Array<{
    alternative: string;
    reason: string;
  }>;
  role: "architect" | "implementer" | "refactor" | "release" | "reviewer" | "scanner" | "security" | "tester";
  session_id?: string;
  summary: string;
  task_id?: string;
  timestamp: string;
  verification?: Array<BrickManifestVerificationEvent>;
});

export type BrickManifestVerificationEvent = ({
  command: string;
  notes?: string;
  output_path?: string;
  status: "blocked" | "fail" | "pass" | "passing" | "skipped";
  timestamp?: string;
});

export type BrickManifest = ({
  boundaries: {
    allowed_side_effects?: Array<string>;
    forbidden_imports?: Array<string>;
    owned_paths: Array<string>;
    private_paths: Array<string>;
    public_paths: Array<string>;
  };
  brick: ({
    domain?: Array<string>;
    frameworks?: Array<string>;
    id: string;
    kind: "adapter" | "capsule" | "guard" | "module_group" | "module" | "submodule" | "template" | "tooling";
    language: Array<string>;
    name: string;
    registry_origin?: string;
    replication?: ({
      auto_pr_on_minor?: boolean;
      auto_pr_on_patch?: boolean;
      deprecation_window_days?: number;
      notify_owners?: Array<string>;
      policy?: "fork-snapshot" | "manual" | "pin-version" | "track-canonical";
    });
    status: "candidate" | "canonical" | "duplicate" | "experimental" | "legacy" | "project_bound" | "variant";
    version: string;
  });
  classification: ({
    data_classes: (Array<"admin_only" | "credential" | "health_sensitive" | "org_private" | "payment" | "pii" | "public" | "regulated" | "user_private">);
    notes?: string;
    risk: "critical" | "high" | "low" | "medium";
  });
  clone: ({
    adaptation_points: Array<string>;
    install_steps: Array<string>;
    known_traps: Array<string>;
    readiness: "blocked" | "copy_ready" | "guided" | "manual_only";
  });
  hierarchy?: ({
    component_policy?: "internal_by_default" | "manifest_required" | "public_component_brick";
    contains?: (Array<"adapter" | "brick" | "component" | "file" | "hook" | "module" | "service" | "submodule" | "utility">);
    group_id?: string;
    level: "brick_group" | "brick" | "component" | "module" | "submodule";
    notes?: string;
    parent_brick_id?: string;
    parent_module_id?: string;
  });
  interfaces: {
    adapters?: Array<string>;
    forbidden_dependencies?: Array<string>;
    ports?: Array<string>;
    public_api?: Array<string>;
    required_dependencies?: Array<string>;
  };
  license?: ({
    attribution_required?: boolean;
    commercial_use?: boolean;
    inherited_from?: string;
    notes?: string;
    openness: "closed" | "open" | "source-available";
    redistribute?: "allowed" | "forbidden" | "with-attribution";
    spdx: string;
    visibility?: "community" | "internal" | "private" | "public";
  });
  owner: {
    primary: string;
    reviewers?: Array<string>;
    team?: string;
  };
  provenance: ({
    created_by: BrickManifestTouchEvent;
    reviewed_by: Array<BrickManifestTouchEvent>;
    seal?: BrickManifestProvenanceSeal;
    source_chain: (Array<({
      brick_id: string;
      commit?: string;
      event?: "copied" | "created" | "forked" | "merged" | "promoted";
      path?: string;
      project: string;
      timestamp?: string;
    })>);
    touched_by: Array<BrickManifestTouchEvent>;
  });
  quality: ({
    code_budget: ({
      dependency_count: number;
      estimate_method?: string;
      exceptions?: Array<string>;
      feature_lines: number;
      file_count: number;
      last_estimated_at?: string;
      notes?: string;
      realistic_regenerate_tokens_estimate?: number;
      static_tokens_estimate?: number;
      status: "acceptable" | "bloated" | "lean" | "unknown";
    });
    line_count: {
      max_file_lines: number;
      over_600_count: number;
    };
    score: number;
    test_commands: Array<string>;
    verification: Array<BrickManifestVerificationEvent>;
  });
  schema_version: "1.0.0";
  security: ({
    env: ({
      required: boolean;
      status: "complete" | "missing" | "not_applicable" | "partial";
      variables: Array<BrickManifestEnvVar>;
    });
    rls: ({
      matrix_path?: string;
      negative_tests?: Array<string>;
      required: boolean;
      status: "complete" | "missing" | "not_applicable" | "partial";
    });
    vulnerability_findings: {
      critical: number;
      high: number;
      low: number;
      medium: number;
      report_paths?: Array<string>;
    };
  });
  source: {
    archive_hash?: string;
    commit?: string;
    copied_from?: Array<{
      brick_id: string;
      commit?: string;
      copied_at?: string;
      path?: string;
      project: string;
    }>;
    paths: Array<string>;
    project: string;
    repository?: string;
  };
  supply_chain: ({
    checksums: Array<{
      path: string;
      sha256: string;
    }>;
    dependencies: (Array<({
      license?: string;
      name: string;
      purpose: string;
      risk?: "high" | "low" | "medium" | "unknown";
      version?: string;
    })>);
    licenses: Array<string>;
    sbom_path?: string;
  });
  sweetspot: {
    sai: BrickManifestGateScore;
    sas: BrickManifestGateScore;
    sev: BrickManifestGateScore;
    spe: BrickManifestGateScore;
    srls: BrickManifestGateScore;
    srs: BrickManifestGateScore;
    ssa_v2: BrickManifestGateScore;
    ssc: BrickManifestGateScore;
    ssi: BrickManifestGateScore;
    ssra: BrickManifestGateScore;
    sstf: BrickManifestGateScore;
    sva: BrickManifestGateScore;
  };
});
