// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export type BuildManifestBuildAlternative = {
  brick_ids: Array<string>;
  notes?: string;
  slot: string;
};

export type BuildManifestBuildBrickRef = ({
  brick_id: string;
  notes?: string;
  order?: number;
  path?: string;
  project?: string;
  required: boolean;
  role: "account_linking" | "admin_checkout_testing" | "admin_gateway" | "admin_shell" | "asset_post_processor" | "asset_proxy" | "auth_callback" | "auth_entrypoint" | "billing_orchestrator" | "billing_ui" | "credits_control" | "delivery_proxy" | "fallback_provider" | "moderation_gate" | "non_prod_auth_stub" | "policy_gate" | "provider_adapter" | "provider_balance_control" | "qa_configuration_control" | "queue_worker" | "rate_limit_control" | "rate_limit_dashboard" | "regression_harness" | "request_orchestrator" | "storage_adapter" | "story_prompting_extension" | "subscription_ui" | "telemetry_facade" | "test_harness" | "ui_surface" | "usage_meter";
});

export type BuildManifestBuildFlow = {
  id: string;
  name: string;
  notes?: string;
  steps: Array<BuildManifestBuildStep>;
};

export type BuildManifestBuildSourceEvent = ({
  artifact_id: string;
  artifact_type: "brick" | "build" | "fixture" | "release";
  commit?: string;
  event: "composed" | "created" | "forked" | "published" | "referenced" | "superseded" | "verified";
  path?: string;
  project: string;
  timestamp: string;
});

export type BuildManifestBuildStep = {
  brick_refs?: Array<string>;
  id: string;
  inputs?: Array<string>;
  name: string;
  notes?: string;
  order?: number;
  outputs?: Array<string>;
};

export type BuildManifestEnvVar = ({
  example?: string;
  forbidden_in?: (Array<"ci" | "client_bundle" | "docs" | "logs" | "tests">);
  name: string;
  required_in: (Array<"ci" | "local" | "preview" | "production" | "test">);
  scope: "ci_only" | "local_only" | "public_client" | "server_only";
});

export type BuildManifestFileMapEntry = ({
  notes?: string;
  ownership: "adapter" | "extensible" | "managed" | "manual";
  source_path: string;
  target_path: string;
});

export type BuildManifestGateScore = ({
  evidence?: Array<string>;
  notes?: string;
  score: number;
  status: "blocked" | "missing" | "not_applicable" | "partial" | "passing";
});

export type BuildManifestProvenanceSeal = {
  algo: string;
  anchor?: string;
  chain_length?: number;
  events_digest?: string;
  head: string;
  key_id?: string;
  signature?: string;
};

export type BuildManifestTouchEvent = ({
  actor_id: string;
  actor_kind: "agent" | "ai_model" | "automation" | "human" | "tool";
  attestation?: {
    method?: string;
    reference?: string;
  };
  commit?: string;
  files_touched?: Array<string>;
  model?: string;
  provider?: string;
  role: "architect" | "implementer" | "refactor" | "release" | "reviewer" | "scanner" | "security" | "tester";
  session_id?: string;
  summary: string;
  task_id?: string;
  timestamp: string;
});

export type BuildManifestVerificationEvent = ({
  command: string;
  notes?: string;
  output_path?: string;
  status: "blocked" | "fail" | "pass" | "planned" | "skipped" | "verified";
  timestamp?: string;
});

export type BuildManifest = ({
  build: ({
    domain?: Array<string>;
    id: string;
    kind: "capability_build" | "integration_build" | "platform_build" | "reference_build" | "workflow_build";
    name: string;
    runtimes?: (Array<"browser" | "edge" | "electron" | "go" | "node" | "python" | "rust" | "supabase" | "worker">);
    slug: string;
    stability: "evolving" | "frozen" | "hardened" | "stable";
    status: "candidate" | "canonical" | "deprecated" | "experimental" | "unsafe" | "verified";
    summary?: string;
    trust_tier?: "canonical" | "experimental" | "reviewed" | "verified";
    version: string;
    visibility: "community" | "internal" | "private" | "public";
  });
  classification: ({
    data_classes: (Array<"admin_only" | "credential" | "health_sensitive" | "org_private" | "payment" | "pii" | "public" | "regulated" | "user_private">);
    notes?: string;
    risk: "critical" | "high" | "low" | "medium";
  });
  clone: ({
    file_map?: Array<BuildManifestFileMapEntry>;
    greenfield_support: boolean;
    install_steps: Array<string>;
    known_traps?: Array<string>;
    matching_architecture_support?: boolean;
    post_clone_checks: Array<string>;
    readiness: "blocked" | "copy_ready" | "guided" | "manual_only";
    required_ports: Array<string>;
    rollback_steps: Array<string>;
    target_docs?: Array<string>;
  });
  composition: ({
    alternatives?: Array<BuildManifestBuildAlternative>;
    brick_refs: Array<BuildManifestBuildBrickRef>;
    flows: Array<BuildManifestBuildFlow>;
    notes?: string;
    optional_bricks?: Array<BuildManifestBuildBrickRef>;
    shared_contracts: (Array<"analytics" | "auth" | "authz" | "billing" | "env" | "governance" | "moderation" | "provider" | "queue" | "rate_limit" | "session" | "storage" | "telemetry" | "ui">);
    topology?: "event_driven" | "fanout" | "hub_and_spoke" | "hub_spoke" | "hybrid" | "linear" | "orchestrated_flow" | "pipeline";
  });
  contracts: ({
    auth: {
      modes: Array<string>;
      notes?: string;
      required: boolean;
      roles?: Array<string>;
    };
    data: {
      inputs: Array<string>;
      outputs: Array<string>;
      retention?: string;
      stores: Array<string>;
      tables?: Array<string>;
    };
    env: {
      forbidden: Array<string>;
      optional: Array<BuildManifestEnvVar>;
      required: Array<BuildManifestEnvVar>;
    };
    network: {
      inbound_endpoints?: Array<string>;
      outbound_hosts: Array<string>;
      webhooks: Array<string>;
    };
    performance: {
      concurrency_hint?: number;
      latency_budget_ms: number;
      notes?: string;
      queue_allowed: boolean;
    };
    rls: ({
      matrix_path?: string;
      negative_tests?: Array<string>;
      required: boolean;
      status: "complete" | "missing" | "not_applicable" | "partial";
      tables?: Array<string>;
    });
  });
  economics: {
    estimated_clone_time_minutes: number;
    estimated_prompt_token_savings: number;
    estimated_update_time_minutes?: number;
    maintenance_score: number;
    notes?: string;
  };
  interfaces: {
    api_endpoints?: Array<string>;
    commands?: Array<string>;
    entrypoints?: Array<string>;
    events?: Array<string>;
    ui_surfaces?: Array<string>;
  };
  owner: {
    primary: string;
    reviewers?: Array<string>;
    team?: string;
  };
  provenance: {
    created_by: BuildManifestTouchEvent;
    reviewed_by: Array<BuildManifestTouchEvent>;
    seal?: BuildManifestProvenanceSeal;
    source_chain: Array<BuildManifestBuildSourceEvent>;
    touched_by: Array<BuildManifestTouchEvent>;
  };
  publishing: ({
    excluded_assets?: Array<string>;
    exposed_docs?: Array<string>;
    lattice?: ({
      computed_at?: string;
      effective_openness?: "closed" | "open" | "source-available";
      effective_visibility?: "community" | "internal" | "private" | "public";
      most_restrictive_brick?: string;
    });
    license: string;
    openness?: "closed" | "open" | "source-available";
    publishable: boolean;
    redaction_profile: "community-default" | "custom" | "internal-default" | "public-hardened";
    visibility: "community" | "internal" | "private" | "public";
  });
  schema_version: "1.0.0";
  source: {
    archive_hash?: string;
    commit?: string;
    derived_from_bricks: Array<BuildManifestBuildBrickRef>;
    paths: Array<string>;
    project: string;
    repository?: string;
    supporting_artifacts?: Array<string>;
  };
  sweetspot: {
    sai: BuildManifestGateScore;
    sas: BuildManifestGateScore;
    sev: BuildManifestGateScore;
    spe: BuildManifestGateScore;
    srls: BuildManifestGateScore;
    srs: BuildManifestGateScore;
    ssa_v2: BuildManifestGateScore;
    ssc: BuildManifestGateScore;
    ssi: BuildManifestGateScore;
    ssra: BuildManifestGateScore;
    sstf: BuildManifestGateScore;
    sva: BuildManifestGateScore;
  };
  upgrade: ({
    breaking_change_signals?: Array<string>;
    channel: "experimental" | "minor_safe" | "patch_safe" | "pinned" | "review_required";
    compatibility_policy: "manifested_ports_only" | "manual_adapter_review" | "project_specific" | "same_runtime_family";
    migration_hooks: Array<string>;
    replacement_policy: "automatic_if_contract_compatible" | "manual_only" | "manual_review_if_contract_changes";
    rollback_supported?: boolean;
    supersedes: Array<string>;
  });
  verification: ({
    evidence: Array<BuildManifestVerificationEvent>;
    fixture_targets: Array<string>;
    integration_targets: Array<string>;
    last_verified_at?: string;
    smoke_commands: Array<string>;
    status: "blocked" | "canonical" | "missing" | "partial" | "planned" | "verified";
  });
});
