// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface BuildManifestBuildAlternative {
  brick_ids: string[];
  notes?: string;
  slot: string;
}

export interface BuildManifestBuildBrickRef {
  brick_id: string;
  notes?: string;
  order?: number;
  path?: string;
  project?: string;
  required: boolean;
  role: "account_linking" | "admin_checkout_testing" | "admin_gateway" | "admin_shell" | "asset_post_processor" | "asset_proxy" | "auth_callback" | "auth_entrypoint" | "billing_orchestrator" | "billing_ui" | "credits_control" | "delivery_proxy" | "fallback_provider" | "moderation_gate" | "non_prod_auth_stub" | "policy_gate" | "provider_adapter" | "provider_balance_control" | "qa_configuration_control" | "queue_worker" | "rate_limit_control" | "rate_limit_dashboard" | "regression_harness" | "request_orchestrator" | "storage_adapter" | "story_prompting_extension" | "subscription_ui" | "telemetry_facade" | "test_harness" | "ui_surface" | "usage_meter";
}

export interface BuildManifestBuildFlow {
  id: string;
  name: string;
  notes?: string;
  steps: BuildManifestBuildStep[];
}

export interface BuildManifestBuildSourceEvent {
  artifact_id: string;
  artifact_type: "brick" | "build" | "fixture" | "release";
  commit?: string;
  event: "composed" | "created" | "forked" | "published" | "referenced" | "superseded" | "verified";
  path?: string;
  project: string;
  timestamp: string;
}

export interface BuildManifestBuildStep {
  brick_refs?: string[];
  id: string;
  inputs?: string[];
  name: string;
  notes?: string;
  order?: number;
  outputs?: string[];
}

export interface BuildManifestEnvVar {
  example?: string;
  forbidden_in?: (("ci" | "client_bundle" | "docs" | "logs" | "tests")[]);
  name: string;
  required_in: (("ci" | "local" | "preview" | "production" | "test")[]);
  scope: "ci_only" | "local_only" | "public_client" | "server_only";
}

export interface BuildManifestFileMapEntry {
  notes?: string;
  ownership: "adapter" | "extensible" | "managed" | "manual";
  source_path: string;
  target_path: string;
}

export interface BuildManifestGateScore {
  evidence?: string[];
  notes?: string;
  score: number;
  status: "blocked" | "missing" | "not_applicable" | "partial" | "passing";
}

export interface BuildManifestProvenanceSeal {
  algo: string;
  anchor?: string;
  chain_length?: number;
  events_digest?: string;
  head: string;
  key_id?: string;
  signature?: string;
}

export interface BuildManifestTouchEvent {
  actor_id: string;
  actor_kind: "agent" | "ai_model" | "automation" | "human" | "tool";
  attestation?: {
    method?: string;
    reference?: string;
  };
  commit?: string;
  files_touched?: string[];
  model?: string;
  provider?: string;
  role: "architect" | "implementer" | "refactor" | "release" | "reviewer" | "scanner" | "security" | "tester";
  session_id?: string;
  summary: string;
  task_id?: string;
  timestamp: string;
}

export interface BuildManifestVerificationEvent {
  command: string;
  notes?: string;
  output_path?: string;
  status: "blocked" | "fail" | "pass" | "planned" | "skipped" | "verified";
  timestamp?: string;
}

export interface BuildManifest {
  build: ({
    domain?: string[];
    id: string;
    kind: "capability_build" | "integration_build" | "platform_build" | "reference_build" | "workflow_build";
    name: string;
    runtimes?: (("browser" | "edge" | "electron" | "go" | "node" | "python" | "rust" | "supabase" | "worker")[]);
    slug: string;
    stability: "evolving" | "frozen" | "hardened" | "stable";
    status: "candidate" | "canonical" | "deprecated" | "experimental" | "unsafe" | "verified";
    summary?: string;
    trust_tier?: "canonical" | "experimental" | "reviewed" | "verified";
    version: string;
    visibility: "community" | "internal" | "private" | "public";
  });
  classification: ({
    data_classes: (("admin_only" | "credential" | "health_sensitive" | "org_private" | "payment" | "pii" | "public" | "regulated" | "user_private")[]);
    notes?: string;
    risk: "critical" | "high" | "low" | "medium";
  });
  clone: ({
    file_map?: BuildManifestFileMapEntry[];
    greenfield_support: boolean;
    install_steps: string[];
    known_traps?: string[];
    matching_architecture_support?: boolean;
    post_clone_checks: string[];
    readiness: "blocked" | "copy_ready" | "guided" | "manual_only";
    required_ports: string[];
    rollback_steps: string[];
    target_docs?: string[];
  });
  composition: ({
    alternatives?: BuildManifestBuildAlternative[];
    brick_refs: BuildManifestBuildBrickRef[];
    flows: BuildManifestBuildFlow[];
    notes?: string;
    optional_bricks?: BuildManifestBuildBrickRef[];
    shared_contracts: (("analytics" | "auth" | "authz" | "billing" | "env" | "governance" | "moderation" | "provider" | "queue" | "rate_limit" | "session" | "storage" | "telemetry" | "ui")[]);
    topology?: "event_driven" | "fanout" | "hub_and_spoke" | "hub_spoke" | "hybrid" | "linear" | "orchestrated_flow" | "pipeline";
  });
  contracts: ({
    auth: {
      modes: string[];
      notes?: string;
      required: boolean;
      roles?: string[];
    };
    data: {
      inputs: string[];
      outputs: string[];
      retention?: string;
      stores: string[];
      tables?: string[];
    };
    env: {
      forbidden: string[];
      optional: BuildManifestEnvVar[];
      required: BuildManifestEnvVar[];
    };
    network: {
      inbound_endpoints?: string[];
      outbound_hosts: string[];
      webhooks: string[];
    };
    performance: {
      concurrency_hint?: number;
      latency_budget_ms: number;
      notes?: string;
      queue_allowed: boolean;
    };
    rls: ({
      matrix_path?: string;
      negative_tests?: string[];
      required: boolean;
      status: "complete" | "missing" | "not_applicable" | "partial";
      tables?: string[];
    });
  });
  economics: {
    estimated_clone_time_minutes: number;
    estimated_prompt_token_savings: number;
    estimated_update_time_minutes?: number;
    maintenance_score: number;
    notes?: string;
  };
  interfaces: {
    api_endpoints?: string[];
    commands?: string[];
    entrypoints?: string[];
    events?: string[];
    ui_surfaces?: string[];
  };
  owner: {
    primary: string;
    reviewers?: string[];
    team?: string;
  };
  provenance: {
    created_by: BuildManifestTouchEvent;
    reviewed_by: BuildManifestTouchEvent[];
    seal?: BuildManifestProvenanceSeal;
    source_chain: BuildManifestBuildSourceEvent[];
    touched_by: BuildManifestTouchEvent[];
  };
  publishing: ({
    excluded_assets?: string[];
    exposed_docs?: string[];
    lattice?: ({
      computed_at?: string;
      effective_openness?: "closed" | "open" | "source-available";
      effective_visibility?: "community" | "internal" | "private" | "public";
      most_restrictive_brick?: string;
    });
    license: string;
    openness?: "closed" | "open" | "source-available";
    publishable: boolean;
    redaction_profile: "community-default" | "custom" | "internal-default" | "public-hardened";
    visibility: "community" | "internal" | "private" | "public";
  });
  schema_version: "1.0.0";
  source: {
    archive_hash?: string;
    commit?: string;
    derived_from_bricks: BuildManifestBuildBrickRef[];
    paths: string[];
    project: string;
    repository?: string;
    supporting_artifacts?: string[];
  };
  sweetspot: {
    sai: BuildManifestGateScore;
    sas: BuildManifestGateScore;
    sev: BuildManifestGateScore;
    spe: BuildManifestGateScore;
    srls: BuildManifestGateScore;
    srs: BuildManifestGateScore;
    ssa_v2: BuildManifestGateScore;
    ssc: BuildManifestGateScore;
    ssi: BuildManifestGateScore;
    ssra: BuildManifestGateScore;
    sstf: BuildManifestGateScore;
    sva: BuildManifestGateScore;
  };
  upgrade: ({
    breaking_change_signals?: string[];
    channel: "experimental" | "minor_safe" | "patch_safe" | "pinned" | "review_required";
    compatibility_policy: "manifested_ports_only" | "manual_adapter_review" | "project_specific" | "same_runtime_family";
    migration_hooks: string[];
    replacement_policy: "automatic_if_contract_compatible" | "manual_only" | "manual_review_if_contract_changes";
    rollback_supported?: boolean;
    supersedes: string[];
  });
  verification: ({
    evidence: BuildManifestVerificationEvent[];
    fixture_targets: string[];
    integration_targets: string[];
    last_verified_at?: string;
    smoke_commands: string[];
    status: "blocked" | "canonical" | "missing" | "partial" | "planned" | "verified";
  });
}
