// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

import type { BrickManifest } from "./brick.manifest.schema.js";

export type CapsuleManifestSchema = (BrickManifest & {
  brick: {
    kind: "capsule";
  };
});
