// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export type DependentsIndex = ({
  dependents: (Record<string, unknown> & Record<string, (Array<({
    drift?: {
      files_changed?: number;
      last_local_modification?: string;
      loc_added?: number;
      loc_removed?: number;
    };
    evidence_kind: "import-lock" | "manual" | "provenance-source-chain" | "reuse-receipt";
    evidence_path?: string;
    imported_at?: string;
    source_commit_imported?: string;
    target_brick_id?: string;
    target_path?: string;
    target_project: string;
    target_root: string;
    upgrade_status?: "behind-major" | "behind-minor" | "diverged" | "unknown" | "up-to-date";
    version_imported?: string;
  })>)>);
  generated_at: string;
  registry_snapshot_sha?: string;
  schema_version: "1.0.0";
  sources: (Record<string, unknown> & Record<string, ({
    dependent_count?: number;
    latest_release_artifact?: string;
    latest_version?: string;
    replication_policy?: "fork-snapshot" | "manual" | "pin-version" | "track-canonical";
    source_path?: string;
    source_project?: string;
  })>);
  stats: {
    import_locks_found?: number;
    projects_scanned?: number;
    reuse_receipts_found?: number;
    total_dependent_links?: number;
    unique_source_bricks?: number;
  };
});
