// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface EntitlementSchema {
  capability: string;
  decision: "allow" | "deny";
  entitlement_id: string;
  expires_at?: string;
  issued_at: string;
  metadata?: Record<string, unknown>;
  schema_version: "1.0.0";
  source: {
    policy: string;
    provider: string;
  };
  subject: ({
    id: string;
    kind: "organization" | "service" | "user";
  });
}
