import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const outputRoot = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(outputRoot, "../../..");
const schemasRoot = path.join(repoRoot, "schemas");
const checkMode = process.argv.slice(2).includes("--check");
const HEADER = "// Generated by tools/lib/schema-types/generate.mjs. Do not edit.\n\n";

/**
 * @typedef {object} JsonSchemaObject
 * @property {string | string[]} [type]
 * @property {unknown} [const]
 * @property {unknown[]} [enum]
 * @property {string} [$ref]
 * @property {string[]} [required]
 * @property {Record<string, JsonSchema>} [properties]
 * @property {Record<string, JsonSchema>} [definitions]
 * @property {Record<string, JsonSchema>} [$defs]
 * @property {boolean | JsonSchemaObject} [additionalProperties]
 * @property {JsonSchema[]} [prefixItems]
 * @property {boolean | JsonSchema | JsonSchema[]} [items]
 * @property {JsonSchema[]} [oneOf]
 * @property {JsonSchema[]} [anyOf]
 * @property {JsonSchema[]} [allOf]
 */
/** @typedef {boolean | JsonSchemaObject} JsonSchema */
/** @typedef {{ fileName: string, schema: JsonSchemaObject, rootTypeName: string, definitionNames: Map<string, string>, imports: Map<string, string> }} SchemaDocument */
/** @typedef {Map<string, SchemaDocument>} SchemaDocuments */
/** @typedef {Map<string, string>} GeneratedOutputs */

/** @param {unknown} value @returns {string} */
function toPascalCase(value) {
  const words = String(value).replace(/\.schema$/, "").match(/[A-Za-z0-9]+/g) || [];
  const name = words.map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join("");
  if (!name) throw new Error(`cannot derive a TypeScript name from ${JSON.stringify(value)}`);
  return /^\d/.test(name) ? `Schema${name}` : name;
}

/** @param {string} fileName @returns {string} */
function schemaTypeName(fileName) {
  return toPascalCase(fileName.replace(/\.json$/, ""));
}

/** @param {string} fileName @returns {string} */
function outputFileName(fileName) {
  return fileName.replace(/\.json$/, ".d.ts");
}

/** @param {string} fileName @returns {string} */
function moduleSpecifier(fileName) {
  return `./${fileName.replace(/\.json$/, ".js")}`;
}

/** @param {unknown} value @returns {string} */
function literal(value) {
  if (value === undefined) return "undefined";
  return JSON.stringify(value) ?? "undefined";
}

/** @param {string} value @param {number} [spaces] @returns {string} */
function indent(value, spaces = 2) {
  const prefix = " ".repeat(spaces);
  return value.split("\n").map((line) => `${prefix}${line}`).join("\n");
}

/** @param {string} value @returns {string} */
function parenthesize(value) {
  return /[|&]/.test(value) ? `(${value})` : value;
}

/** @param {string} value @returns {string} */
function propertyName(value) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

/** @param {string} value @returns {string} */
function decodePointerToken(value) {
  return decodeURIComponent(value).replace(/~1/g, "/").replace(/~0/g, "~");
}

/** @param {JsonSchemaObject} schema @param {string} fragment @param {string} ref @returns {unknown} */
function resolvePointer(schema, fragment, ref) {
  if (!fragment || fragment === "#") return schema;
  if (!fragment.startsWith("#/")) throw new Error(`unsupported JSON Schema reference ${ref}`);
  /** @type {unknown} */
  let current = schema;
  for (const token of fragment.slice(2).split("/").map(decodePointerToken)) {
    if (!current || typeof current !== "object" || !(token in current)) {
      throw new Error(`unresolved JSON Schema reference ${ref}`);
    }
    current = /** @type {Record<string, unknown>} */ (current)[token];
  }
  return current;
}

/** @param {JsonSchemaObject} schema @returns {Array<[string, JsonSchema]>} */
function definitionEntries(schema) {
  return /** @type {Array<[string, JsonSchema]>} */ (Object.entries({ ...(schema.definitions || {}), ...(schema.$defs || {}) }))
    .sort(([left], [right]) => left.localeCompare(right));
}

/** @param {SchemaDocument} document @param {string} definitionName @returns {string} */
function definitionTypeName(document, definitionName) {
  const typeName = document.definitionNames.get(definitionName);
  if (!typeName) throw new Error(`unknown definition ${definitionName} in ${document.fileName}`);
  return typeName;
}

/** @param {string} fragment @returns {string | null} */
function parseDefinitionPointer(fragment) {
  const match = /^#\/(?:\$defs|definitions)\/([^/]+)$/.exec(fragment);
  return match ? decodePointerToken(match[1]) : null;
}

/** @param {string} ref @param {SchemaDocument} document @param {SchemaDocuments} documents @returns {string} */
function resolveRef(ref, document, documents) {
  const hashIndex = ref.indexOf("#");
  const filePart = hashIndex === -1 ? ref : ref.slice(0, hashIndex);
  const fragment = hashIndex === -1 ? "" : ref.slice(hashIndex);
  let target = document;

  if (filePart) {
    const absolutePath = path.resolve(schemasRoot, path.dirname(document.fileName), decodeURIComponent(filePart));
    const relativePath = path.relative(schemasRoot, absolutePath).split(path.sep).join("/");
    if (relativePath.startsWith("../") || path.isAbsolute(relativePath)) {
      throw new Error(`external JSON Schema reference is not allowed: ${ref}`);
    }
    const resolvedTarget = documents.get(relativePath);
    if (!resolvedTarget) throw new Error(`referenced schema does not exist: ${ref}`);
    target = resolvedTarget;
  }

  if (!fragment || fragment === "#") {
    if (target !== document) document.imports.set(target.rootTypeName, moduleSpecifier(target.fileName));
    return target.rootTypeName;
  }
  const definitionName = parseDefinitionPointer(fragment);
  if (definitionName) {
    const typeName = definitionTypeName(target, definitionName);
    if (target !== document) document.imports.set(typeName, moduleSpecifier(target.fileName));
    return typeName;
  }

  if (target !== document) {
    throw new Error(`cross-schema references must target a schema root or definition: ${ref}`);
  }

  return renderType(resolvePointer(target.schema, fragment, ref), target, documents);
}

/** @param {JsonSchemaObject} schema @param {SchemaDocument} document @param {SchemaDocuments} documents @returns {string} */
function renderObject(schema, document, documents) {
  const required = new Set(schema.required || []);
  const properties = Object.entries(schema.properties || {})
    .sort(([left], [right]) => left.localeCompare(right));
  const fields = properties.map(([name, propertySchema]) => {
    const optional = required.has(name) ? "" : "?";
    return `${propertyName(name)}${optional}: ${renderType(propertySchema, document, documents)};`;
  });
  const objectType = fields.length > 0
    ? `{\n${indent(fields.join("\n"))}\n}`
    : schema.additionalProperties === false
      ? "Record<string, never>"
      : "Record<string, unknown>";

  if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
    const values = renderType(schema.additionalProperties, document, documents);
    return `${parenthesize(objectType)} & Record<string, ${values}>`;
  }
  return objectType;
}

/** @param {JsonSchemaObject} schema @param {SchemaDocument} document @param {SchemaDocuments} documents @returns {string} */
function renderArray(schema, document, documents) {
  if (Array.isArray(schema.prefixItems)) {
    return `[${schema.prefixItems.map((entry) => renderType(entry, document, documents)).join(", ")}]`;
  }
  if (Array.isArray(schema.items)) {
    return `[${schema.items.map((entry) => renderType(entry, document, documents)).join(", ")}]`;
  }
  const itemType = schema.items === false
    ? "never"
    : renderType(schema.items || {}, document, documents);
  return `Array<${itemType}>`;
}

/** @param {JsonSchemaObject} schema @param {string} type @param {SchemaDocument} document @param {SchemaDocuments} documents @returns {string} */
function renderPrimitive(schema, type, document, documents) {
  switch (type) {
    case "null": return "null";
    case "boolean": return "boolean";
    case "integer":
    case "number": return "number";
    case "string": return "string";
    case "array": return renderArray(schema, document, documents);
    case "object": return renderObject(schema, document, documents);
    default: throw new Error(`unsupported JSON Schema type ${JSON.stringify(type)} in ${document.fileName}`);
  }
}

/** @param {JsonSchemaObject} schema @returns {boolean} */
function hasBaseType(schema) {
  return Boolean(schema.type || schema.properties || schema.additionalProperties !== undefined || schema.items || schema.prefixItems);
}

/** @param {unknown} schema @param {SchemaDocument} document @param {SchemaDocuments} documents @returns {string} */
function renderType(schema, document, documents) {
  if (schema === true) return "unknown";
  if (schema === false) return "never";
  if (!schema || typeof schema !== "object") return "unknown";
  const schemaObject = /** @type {JsonSchemaObject} */ (schema);
  if (Object.hasOwn(schemaObject, "const")) return literal(schemaObject.const);
  if (Array.isArray(schemaObject.enum)) {
    return [...schemaObject.enum].sort((left, right) => literal(left).localeCompare(literal(right))).map(literal).join(" | ") || "never";
  }

  /** @type {string[]} */
  const intersections = [];
  if (schemaObject.$ref) intersections.push(resolveRef(schemaObject.$ref, document, documents));
  if (Array.isArray(schemaObject.oneOf)) {
    intersections.push(schemaObject.oneOf.map((entry) => parenthesize(renderType(entry, document, documents))).join(" | "));
  }
  if (Array.isArray(schemaObject.anyOf)) {
    intersections.push(schemaObject.anyOf.map((entry) => parenthesize(renderType(entry, document, documents))).join(" | "));
  }
  if (Array.isArray(schemaObject.allOf)) {
    intersections.push(schemaObject.allOf.map((entry) => parenthesize(renderType(entry, document, documents))).join(" & "));
  }
  if (hasBaseType(schemaObject)) {
    const types = Array.isArray(schemaObject.type) ? [...schemaObject.type] : [schemaObject.type || "object"];
    intersections.push(types.sort().map((type) => renderPrimitive(schemaObject, type, document, documents)).join(" | "));
  }

  return intersections.filter(Boolean).map(parenthesize).join(" & ") || "unknown";
}

/** @param {SchemaDocument} document @param {SchemaDocuments} documents @returns {string} */
function renderDocument(document, documents) {
  document.imports.clear();
  const declarations = definitionEntries(document.schema).map(([name, definition]) =>
    `export type ${definitionTypeName(document, name)} = ${renderType(definition, document, documents)};`
  );
  declarations.push(`export type ${document.rootTypeName} = ${renderType(document.schema, document, documents)};`);
  const imports = [...document.imports]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([typeName, specifier]) => `import type { ${typeName} } from ${JSON.stringify(specifier)};`);
  return `${HEADER}${imports.length > 0 ? `${imports.join("\n")}\n\n` : ""}${declarations.join("\n\n")}\n`;
}

async function loadDocuments() {
  const fileNames = (await fs.readdir(schemasRoot)).filter((name) => name.endsWith(".json")).sort();
  /** @type {SchemaDocuments} */
  const documents = new Map();
  for (const fileName of fileNames) {
    const schema = /** @type {JsonSchemaObject} */ (JSON.parse(await fs.readFile(path.join(schemasRoot, fileName), "utf8")));
    const rootTypeName = schemaTypeName(fileName);
    /** @type {Map<string, string>} */
    const definitionNames = new Map();
    const usedNames = new Set([rootTypeName]);
    for (const [name] of definitionEntries(schema)) {
      const typeName = `${rootTypeName}${toPascalCase(name)}`;
      if (usedNames.has(typeName)) throw new Error(`duplicate generated type name ${typeName} in ${fileName}`);
      usedNames.add(typeName);
      definitionNames.set(name, typeName);
    }
    documents.set(fileName, { fileName, schema, rootTypeName, definitionNames, imports: new Map() });
  }
  return documents;
}

/** @param {SchemaDocuments} documents @returns {string} */
function renderIndex(documents) {
  const exports = [...documents.values()].map((document) => `export * from ${JSON.stringify(moduleSpecifier(document.fileName))};`);
  return `${HEADER}${exports.join("\n")}\n`;
}

/** @param {string} targetRoot @param {GeneratedOutputs} outputs */
async function writeOutputs(targetRoot, outputs) {
  await fs.mkdir(targetRoot, { recursive: true });
  await Promise.all([...outputs].map(([name, content]) => fs.writeFile(path.join(targetRoot, name), content)));
}

/** @param {GeneratedOutputs} outputs */
async function checkOutputs(outputs) {
  const tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "smarch-schema-types-"));
  try {
    await writeOutputs(tempRoot, outputs);
    const committed = (await fs.readdir(outputRoot)).filter((name) => name.endsWith(".d.ts")).sort();
    const generated = [...outputs.keys()].sort();
    const stale = new Set([...committed, ...generated]);
    /** @type {string[]} */
    const differences = [];
    for (const name of [...stale].sort()) {
      const [actual, expected] = await Promise.all([
        fs.readFile(path.join(outputRoot, name), "utf8").catch(() => null),
        fs.readFile(path.join(tempRoot, name), "utf8").catch(() => null),
      ]);
      if (actual !== expected) differences.push(name);
    }
    if (differences.length > 0) {
      console.error(`schema type declarations are stale: ${differences.join(", ")}`);
      process.exitCode = 1;
      return;
    }
    console.log(`schema type declarations are current (${generated.length - 1} schemas)`);
  } finally {
    await fs.rm(tempRoot, { recursive: true, force: true });
  }
}

async function generate() {
  const documents = await loadDocuments();
  /** @type {GeneratedOutputs} */
  const outputs = new Map();
  for (const document of documents.values()) {
    outputs.set(outputFileName(document.fileName), renderDocument(document, documents));
  }
  outputs.set("index.d.ts", renderIndex(documents));

  if (checkMode) {
    await checkOutputs(outputs);
    return;
  }

  const existing = (await fs.readdir(outputRoot)).filter((name) => name.endsWith(".d.ts"));
  await Promise.all(existing.filter((name) => !outputs.has(name)).map((name) => fs.rm(path.join(outputRoot, name))));
  await writeOutputs(outputRoot, outputs);
  console.log(`generated ${documents.size} schema type declarations`);
}

await generate();
