// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface GlobalRegistry {
  bricks: ({
    brick_group?: (null | string);
    clone_readiness?: string;
    data_classes?: string[];
    domain?: string[];
    feature_cluster?: {
      description: string;
      id: string;
      name: string;
    };
    health?: ({
      calculated_score?: (number | null);
      error_count: number;
      errors?: string[];
      status: "fail" | "ok" | "warn";
      warning_count: number;
      warnings?: string[];
    });
    hierarchy?: (null | Record<string, unknown>);
    id: string;
    kind?: string;
    manifest_path: string;
    models?: string[];
    name: string;
    project?: string;
    risk?: string;
    score?: number;
    source_paths?: string[];
    status: string;
  }[]);
  candidate_group_count?: number;
  candidate_groups?: ({
    candidate_count: number;
    candidate_role_counts?: (Record<string, unknown> & Record<string, number>);
    candidate_type_counts?: (Record<string, unknown> & Record<string, number>);
    id: string;
    name: string;
    path: string;
    project: string;
    sample_paths?: string[];
  }[]);
  count?: number;
  failure_count?: number;
  failures?: {
    error: string;
    manifest_path: string;
  }[];
  generated_at: string;
  projects: ({
    average_score?: number;
    brick_count?: number;
    candidate_group_count?: number;
    candidate_role_counts?: (Record<string, unknown> & Record<string, number>);
    candidate_type_counts?: (Record<string, unknown> & Record<string, number>);
    error_count?: number;
    health_counts?: (Record<string, unknown> & Record<string, number>);
    id: string;
    repository?: string;
    root: string;
    security_gate?: {
      findings: number;
      high_or_critical: number;
      scanned_files?: number;
      status: string;
      truncated?: boolean;
    };
    status_counts?: (Record<string, unknown> & Record<string, number>);
    unmanifested_count?: number;
    warning_count?: number;
  }[]);
  scan_project_id?: (null | string);
  scan_root?: string;
  scanned_project_roots?: {
    id: string;
    root: string;
  }[];
  schema_version: "1.0.0";
  unmanifested_bricks?: {
    brick_group?: string;
    candidate_type: string;
    group_name?: string;
    group_path?: string;
    hierarchy_role?: string;
    path: string;
    project: string;
    reason: string;
    relative_path?: string;
    status: "unmanifested";
  }[];
  unmanifested_count?: number;
  validation_error_count?: number;
  validation_warning_count?: number;
}
