// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface ImportLockActorRecord {
  actor: string;
  model?: string;
  tool?: string;
}

export type ImportLockArtifactId = string;

export type ImportLockArtifactType = "brick" | "build";

export type ImportLockHashLike = string;

export interface ImportLockLockedArtifact {
  artifact_id: ImportLockArtifactId;
  artifact_type: ImportLockArtifactType;
  channel?: "alpha" | "beta" | "candidate" | "dev" | "hotfix" | "lts" | "stable";
  import_id: string;
  local_overrides?: number;
  release_hash?: ImportLockHashLike;
  release_version: ImportLockSemver;
  source_project?: string;
  trust_tier?: "candidate" | "canonical" | "experimental" | "verified";
  verification_status?: "candidate" | "canonical" | "failed" | "unverified" | "verified";
}

export type ImportLockLockedBrick = (ImportLockLockedArtifact & {
  artifact_type?: "brick";
});

export type ImportLockLockedBuild = (ImportLockLockedArtifact & {
  artifact_type?: "build";
});

export type ImportLockSemver = string;

export interface ImportLock {
  channels?: ({
    artifact_id: ImportLockArtifactId;
    artifact_type: ImportLockArtifactType;
    channel: "alpha" | "beta" | "candidate" | "dev" | "hotfix" | "lts" | "stable";
  }[]);
  frozen_dependency_graph: ({
    edges: ({
      from: string;
      relation: "adapter_for" | "alternative_to" | "composes_with" | "depends_on" | "optional";
      to: string;
    }[]);
    nodes: {
      artifact_id: ImportLockArtifactId;
      artifact_type: ImportLockArtifactType;
      node_id: string;
      release_hash?: ImportLockHashLike;
      release_version: ImportLockSemver;
    }[];
  });
  lock: ({
    generated_at: string;
    generated_by?: ImportLockActorRecord;
    imports_path?: string;
    lock_id?: string;
    mode: "channel" | "exact" | "mixed";
    notes?: string;
    placements_path?: string;
    registry_origin?: string;
    registry_snapshot_sha: ImportLockHashLike;
    update_journal_path?: string;
  });
  resolved_bricks: ImportLockLockedBrick[];
  schema_version: "1.0.0";
  selected_builds: ImportLockLockedBuild[];
  target: {
    commit?: ImportLockHashLike;
    frameworks?: string[];
    id?: string;
    name?: string;
    repository?: string;
    root: string;
    runtimes?: string[];
  };
  trust_policy: ({
    allow_local_overrides: boolean;
    allowed_release_statuses: (("deprecated" | "draft" | "published" | "superseded" | "yanked")[]);
    fail_on_breaking_upgrade?: boolean;
    fail_on_yanked_release?: boolean;
    minimum_verification_status?: "candidate" | "canonical" | "unverified" | "verified";
    require_contract_hashes: boolean;
  });
  verification_policy: ({
    fail_on_contract_delta?: boolean;
    fail_on_missing_env: boolean;
    post_install_checks?: string[];
    required_check_status: "passed" | "skipped" | "warning";
    run_declared_tests: boolean;
    run_env_truthing?: boolean;
    run_import_resolution?: boolean;
    run_rls_truthing?: boolean;
  });
}
