// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface MergeProposal {
  brick_id: string;
  chains: {
    actor_kind?: string;
    agent_id: string;
    chain_id: string;
    ended_at?: string;
    events: string[];
    files_touched?: string[];
    intents: string[];
    lease_ids?: string[];
    model?: string;
    session_id?: string;
    started_at?: string;
  }[];
  files: ({
    diverged_field?: string;
    path: string;
    status: "agreed" | "diverged" | "manifest_field_diverged" | "only_in_chain_a" | "only_in_chain_b";
  }[]);
  generated_at: string;
  project?: string;
  proposal_id: string;
  recommendation: {
    preferred_chain: string;
    reason: string;
  };
  resolution_kind?: "accepted_a" | "accepted_b" | "discarded_a" | "discarded_b" | "fork" | "manual_merge";
  resolution_notes?: string;
  resolved_at?: string;
  resolved_by?: string;
  schema_version: "1.0.0";
}
