// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export type PlacementMapActorRecord = {
  actor: string;
  model?: string;
  tool?: string;
};

export type PlacementMapArtifactId = string;

export type PlacementMapArtifactType = "brick" | "build";

export type PlacementMapHashLike = string;

export type PlacementMapSemver = string;

export type PlacementMap = ({
  imports: (Array<({
    artifact_id: PlacementMapArtifactId;
    artifact_type: PlacementMapArtifactType;
    import_id: string;
    imported_at?: string;
    portable_doc_paths?: Array<string>;
    release_hash?: PlacementMapHashLike;
    release_version: PlacementMapSemver;
    status?: "adapted" | "disabled" | "drifted" | "installed" | "removed";
  })>);
  map: {
    generated_at: string;
    generated_by?: PlacementMapActorRecord;
    imports_path?: string;
    lockfile_path?: string;
    notes?: string;
    registry_snapshot_sha?: PlacementMapHashLike;
  };
  placements: (Array<({
    adapter_points?: (Array<({
      id: string;
      kind: "api" | "auth" | "config" | "event" | "other" | "queue" | "storage" | "telemetry" | "ui_slot";
      required: boolean;
      status: "bound" | "customized" | "pending" | "skipped";
      target_path?: string;
      target_symbol?: string;
    })>);
    alias_rewrites?: Array<{
      from: string;
      to: string;
    }>;
    env_bindings?: (Array<({
      bound_to?: string;
      name: string;
      required: boolean;
      surface: "client" | "edge" | "server" | "shared" | "worker";
    })>);
    exported_symbols?: (Array<({
      kind: "class" | "command" | "component" | "constant" | "function" | "hook" | "other" | "route" | "type";
      name: string;
      source_export?: string;
      target_local?: string;
    })>);
    import_id: string;
    kind: "asset" | "config" | "directory" | "doc" | "file" | "migration" | "test";
    local_overrides?: (Array<({
      kind: "config" | "deleted" | "other" | "patch" | "rename" | "wrapper";
      notes?: string;
      path?: string;
      status: "active" | "merged" | "stale";
    })>);
    ownership: ({
      mode: "adapted" | "forked" | "local" | "managed";
      owner?: string;
      replaceable: boolean;
    });
    placement_id: string;
    source_hash?: PlacementMapHashLike;
    source_path: string;
    target_hash?: PlacementMapHashLike;
    target_path: string;
  })>);
  schema_version: "1.0.0";
  target: {
    id?: string;
    name?: string;
    repository?: string;
    root: string;
    target_runtime?: string;
  };
});
