// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface ProjectIndex {
  modules: ({
    brick_id: string;
    manifest_path: string;
    notes?: string;
    score?: number;
    status: "candidate" | "canonical" | "duplicate" | "experimental" | "legacy" | "project_bound" | "variant";
  }[]);
  project: {
    commit?: string;
    id: string;
    name: string;
    repository?: string;
    root: string;
    stack?: string[];
  };
  schema_version: "1.0.0";
}
