// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export type ProjectIndex = ({
  modules: (Array<({
    brick_id: string;
    manifest_path: string;
    notes?: string;
    score?: number;
    status: "candidate" | "canonical" | "duplicate" | "experimental" | "legacy" | "project_bound" | "variant";
  })>);
  project: {
    commit?: string;
    id: string;
    name: string;
    repository?: string;
    root: string;
    stack?: Array<string>;
  };
  schema_version: "1.0.0";
});
