// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface ReleaseActorRecord {
  actor: string;
  model?: string;
  timestamp?: string;
  tool?: string;
}

export type ReleaseArtifactId = string;

export type ReleaseArtifactType = "brick" | "build";

export type ReleaseHashLike = string;

export type ReleaseSemver = string;

export interface Release {
  content: ({
    artifacts?: ({
      executable?: boolean;
      kind: "asset" | "config" | "directory" | "doc" | "file" | "migration" | "test";
      path: string;
      sha256: ReleaseHashLike;
    }[]);
    entrypoints?: string[];
    included_paths: string[];
    portable_docs?: string[];
  });
  contracts: ({
    data_classes?: (("admin_only" | "credential" | "health_sensitive" | "org_private" | "payment" | "pii" | "public" | "regulated" | "user_private")[]);
    dependency_refs?: {
      artifact_id: ReleaseArtifactId;
      artifact_type: ReleaseArtifactType;
      release_ref?: string;
      required?: boolean;
      version_range?: string;
    }[];
    external_packages?: ({
      name: string;
      scope?: "build" | "dev" | "runtime";
      version_range?: string;
    }[]);
    forbidden_env?: string[];
    hashes: {
      data?: ReleaseHashLike;
      dependencies?: ReleaseHashLike;
      env?: ReleaseHashLike;
      interfaces?: ReleaseHashLike;
      rls?: ReleaseHashLike;
      verification?: ReleaseHashLike;
    };
    optional_env?: string[];
    public_interfaces?: string[];
    required_env?: string[];
    runtimes: string[];
  });
  migration?: {
    commands?: string[];
    manual_steps?: string[];
    notes?: string;
  };
  provenance: ({
    created_by: ReleaseActorRecord;
    reviewed_by?: ReleaseActorRecord[];
    source_chain?: ({
      hash?: ReleaseHashLike;
      kind: "brick" | "build" | "commit" | "doc" | "manifest" | "registry" | "release";
      ref: string;
    }[]);
  });
  release: ({
    artifact_id: ReleaseArtifactId;
    artifact_type: ReleaseArtifactType;
    breaking?: boolean;
    channel: "alpha" | "beta" | "candidate" | "dev" | "hotfix" | "lts" | "stable";
    content_hash: ReleaseHashLike;
    created_at: string;
    notes?: string;
    previous_release?: string;
    published_at?: string;
    registry_origin?: string;
    registry_snapshot_sha: ReleaseHashLike;
    release_id?: string;
    replacement_release?: string;
    source_commit: ReleaseHashLike;
    source_manifest_path?: string;
    source_project?: string;
    status: "deprecated" | "draft" | "published" | "superseded" | "yanked";
    supersedes?: string[];
    version: ReleaseSemver;
  });
  rollback?: {
    artifact_paths?: string[];
    commands?: string[];
    notes?: string;
  };
  schema_version: "1.0.0";
  verification: ({
    checks?: ({
      command?: string;
      evidence_path?: string;
      name: string;
      status: "failed" | "passed" | "skipped";
    }[]);
    fixture_targets?: string[];
    integration_targets?: string[];
    rollback_supported?: boolean;
    smoke_commands?: string[];
    status: "candidate" | "canonical" | "failed" | "unverified" | "verified";
    verified_at?: string;
  });
}
