// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export type ReuseReceipt = ({
  backlog_entry_ids?: Array<string>;
  estimates: ({
    infrastructure_cost_tokens?: number;
    loc_inherited_total: number;
    tokens_saved_estimate: ({
      factors?: (Record<string, unknown> & Record<string, number>);
      lower: number;
      method: string;
      upper: number;
    });
    wall_clock_minutes_saved_estimate?: number;
  });
  generated_at: string;
  id: string;
  items: (Array<({
    files: number;
    kind: "brick" | "build" | "component" | "hook" | "module" | "schema" | "service" | "utility";
    loc: number;
    modified_after_clone?: {
      files_changed?: number;
      loc_added?: number;
      loc_removed?: number;
    };
    source_brick_id: string;
    target_brick_id?: string;
    target_path: string;
    token_estimate?: number;
  })>);
  provenance?: ({
    actor_id?: string;
    actor_kind?: "ai_model" | "automation" | "human";
    model?: string;
    session_id?: string;
  });
  schema_version: "1.0.0";
  source: {
    commit: string;
    project: string;
    registry_path?: string;
  };
  target: {
    commit?: string;
    project: string;
    root: string;
  };
});
