// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export type ServerCardSchema = {
  authorization: {
    boundary: "stdio-parent-process";
    read_capability: "registry:read";
    write_capability: "release:install";
  };
  description: string;
  name: "smarch-registry";
  repository: string;
  tools: Array<string>;
  transport: {
    type: "stdio";
  };
  version: string;
};
