// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface ServerCardSchema {
  authorization: {
    boundary: "stdio-parent-process";
    read_capability: "registry:read";
    write_capability: "release:install";
  };
  description: string;
  name: "smarch-registry";
  repository: string;
  tools: string[];
  transport: {
    type: "stdio";
  };
  version: string;
}
