// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface SubmissionBundleSchemaFile {
  bytes: number;
  path: string;
  role: "attestation" | "checklist" | "manifest" | "source";
  sha256: string;
}

export interface SubmissionBundleSchemaGate {
  command: "npm run gate:all" | "npm run gate:leaks";
  status: 0;
  stderr_sha256: string;
  stdout_sha256: string;
}

export interface SubmissionBundleSchema {
  brick: {
    id: string;
    name: string;
    status: string;
    version: string;
  };
  created_at: string;
  files: SubmissionBundleSchemaFile[];
  kind: "sma.community-submission-bundle";
  schema: "https://sweetspot.local/schemas/submission-bundle/1.0.0-inline";
  schema_version: "1.0.0";
  verification: ({
    digest: "sha256";
    gates: SubmissionBundleSchemaGate[];
    manifest_validator: "tools/sma-validate.ts";
    manifest_warning_count: number;
  });
}
