// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export type WorkforcePacketSchema = ({
  acceptance_criteria: Array<string>;
  constraints: Array<string>;
  design_spec?: string;
  effort: "high" | "low" | "medium" | "xhigh";
  evidence_required: Array<string>;
  forbidden_surfaces: Array<string>;
  mode: "ENSEMBLE" | "SPLIT";
  objective: string;
  review_round?: number;
  schema_version: "1.0.0";
  scope_files: Array<string>;
  task_id: string;
});
