// Generated by tools/lib/schema-types/generate.mjs. Do not edit.

export interface WorkforcePacketSchema {
  acceptance_criteria: string[];
  constraints: string[];
  design_spec?: string;
  effort: "high" | "low" | "medium" | "xhigh";
  evidence_required: string[];
  forbidden_surfaces: string[];
  mode: "ENSEMBLE" | "SPLIT";
  objective: string;
  review_round?: number;
  schema_version: "1.0.0";
  scope_files: string[];
  task_id: string;
}
