#!/usr/bin/env node
/**
 * WHAT: Rebuilds master, project, tag, and archetype indexes for detailed brick pages.
 * WHY: Generated reference pages are difficult to browse unless every project and semantic grouping has a current navigation surface.
 * HOW: Scans existing detailed wiki pages, writes deterministic index files, and is called after the Codex wiki generator.
 * Usage: `node tools/sma-codex-wiki-index.ts --root wiki/bricks-detailed`
 */
/**
 * sma-codex-wiki-index: rebuild the top-level "detailed wiki" indices from
 * all per-brick pages generated by sma-codex-wiki.
 *
 * Outputs:
 *   wiki/bricks-detailed/README.md         — cross-project master index
 *   wiki/bricks-detailed/<project>/INDEX.md — per-project index
 *   wiki/bricks-detailed/TAGS.md            — reverse index by tag
 *   wiki/bricks-detailed/ARCHETYPES.md      — index grouped by reuse_archetype
 *
 * No LLM calls. Pure filesystem scan over the existing *.md pages.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DEFAULT_WIKI_ROOT = path.resolve(__dirname, "../wiki/bricks-detailed");

function parseArgs(argv: string[]) {
  const opts = {
    root: DEFAULT_WIKI_ROOT
  };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i]; const n = argv[i + 1];
    if (a === "--root" && n) { opts.root = path.resolve(n); i += 1; }
  }
  return opts;
}

async function exists(p: string): Promise<boolean> { try { await fs.access(p); return true; } catch { return false; } }

type FrontMatter = Record<string, string | string[]>;
type WikiPage = { project: string; file: string; full: string; fm: FrontMatter; title: string };

function parseFrontMatter(text: string): FrontMatter {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const out: FrontMatter = {};
  for (const line of m[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx < 0) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if (val.startsWith('"') && val.endsWith('"')) val = val.slice(1, -1);
    if (val.startsWith("[") && val.endsWith("]")) {
      try {
        const parsed: unknown = JSON.parse(val);
        if (Array.isArray(parsed) && parsed.every((item) => typeof item === 'string')) out[key] = parsed;
      } catch { /* ignore */ }
      if (Array.isArray(out[key])) continue;
    }
    out[key] = val;
  }
  return out;
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (!(await exists(opts.root))) { console.error(`no wiki root at ${opts.root}`); process.exit(2); }

  const projects = await fs.readdir(opts.root, { withFileTypes: true });
  const pages: WikiPage[] = [];
  for (const p of projects) {
    if (!p.isDirectory()) continue;
    const pdir = path.join(opts.root, p.name);
    const entries = await fs.readdir(pdir);
    for (const e of entries) {
      if (!e.endsWith(".md") || e === "INDEX.md" || e.endsWith(".portable.md")) continue;
      const full = path.join(pdir, e);
      const text = await fs.readFile(full, "utf8");
      const fm = parseFrontMatter(text);
      pages.push({ project: p.name, file: e, full, fm, title: typeof fm.title === 'string' ? fm.title : e.replace(/\.md$/, "") });
    }
  }

  // Per-project index
  const byProject = new Map<string, WikiPage[]>();
  for (const p of pages) {
    const list = byProject.get(p.project) ?? [];
    list.push(p);
    byProject.set(p.project, list);
  }
  for (const [proj, list] of byProject) {
    list.sort((a, b) => a.title.localeCompare(b.title));
    const out = [
      `# ${proj} — detailed brick reference`, "",
      `${list.length} brick page(s). Each page is a full MSDN/rustdoc-style reference with public API, configuration, usage example, integration recipe, troubleshooting, and a portable \`.portable.md\` that can be dropped into a host project's \`docs/\` folder.`, "",
      "| Brick | Status | Kind | Archetype |",
      "|---|---|---|---|",
      ...list.map((p) => `| [${p.title}](${p.file}) | ${p.fm.status || "?"} | ${p.fm.kind || "?"} | ${p.fm.archetype || "?"} |`),
      ""
    ].join("\n");
    await fs.writeFile(path.join(opts.root, proj, "INDEX.md"), out);
  }

  // Top-level master index
  pages.sort((a, b) => (a.project + a.title).localeCompare(b.project + b.title));
  const master = [
    `# SMA detailed brick wiki`, "",
    `Total pages: **${pages.length}** across **${byProject.size}** project(s).`, "",
    `These pages are generated by \`tools/sma-codex-wiki.ts\` using Codex (gpt-5.4). Each page has:`, "",
    `- MSDN/rustdoc-style per-symbol reference (signature, params, returns, throws, remarks, example, see-also)`,
    `- Configuration & env-var matrix`,
    `- Installation + integration recipes`,
    `- Related-brick graph (from \`sma-codex-connect\`)`,
    `- A **portable** \`.portable.md\` variant next to the main page, designed to be copied into the target project's \`docs/\` folder alongside the cloned brick.`,
    "",
    "## Projects", "",
    ...Array.from(byProject.keys()).sort().map((p) => `- [${p}](${p}/INDEX.md) — ${(byProject.get(p) ?? []).length} page(s)`),
    "",
    "## All pages (alphabetical by project/title)", "",
    "| Project | Brick | Status | Archetype |",
    "|---|---|---|---|",
    ...pages.map((p) => `| ${p.project} | [${p.title}](${p.project}/${p.file}) | ${p.fm.status || "?"} | ${p.fm.archetype || "?"} |`),
    ""
  ].join("\n");
  await fs.writeFile(path.join(opts.root, "README.md"), master);

  // Tags index
  const byTag = new Map<string, WikiPage[]>();
  const byArchetype = new Map<string, WikiPage[]>();
  for (const p of pages) {
    const tags = Array.isArray(p.fm.tags) ? p.fm.tags : [];
    for (const t of tags) {
      const key = String(t).toLowerCase();
      const tagged = byTag.get(key) ?? [];
      tagged.push(p);
      byTag.set(key, tagged);
    }
    const arch = typeof p.fm.archetype === 'string' ? p.fm.archetype : "unknown";
    const archetyped = byArchetype.get(arch) ?? [];
    archetyped.push(p);
    byArchetype.set(arch, archetyped);
  }
  const tagLines = [`# Brick tag index`, ""];
  for (const [tag, list] of [...byTag.entries()].sort()) {
    tagLines.push(`## \`${tag}\` (${list.length})`, "");
    for (const p of list) tagLines.push(`- ${p.project} / [${p.title}](${p.project}/${p.file})`);
    tagLines.push("");
  }
  await fs.writeFile(path.join(opts.root, "TAGS.md"), tagLines.join("\n"));

  const archLines = [`# Brick archetype index`, ""];
  for (const [arch, list] of [...byArchetype.entries()].sort()) {
    archLines.push(`## ${arch} (${list.length})`, "");
    for (const p of list) archLines.push(`- ${p.project} / [${p.title}](${p.project}/${p.file})`);
    archLines.push("");
  }
  await fs.writeFile(path.join(opts.root, "ARCHETYPES.md"), archLines.join("\n"));

  console.log(JSON.stringify({ pages: pages.length, projects: byProject.size, tags: byTag.size, archetypes: byArchetype.size, root: opts.root }, null, 2));
}

main().catch((err) => { console.error(err instanceof Error ? err.stack : err); process.exit(1); });
