#!/usr/bin/env node
/**
 * WHAT: One-command adoption — make any existing project consume the SMARCH
 *   engine without vendoring or copying it.
 * WHY: The first question every adopter asks is "how do I use this in MY repo?"
 *   Cloning the whole engine into each project causes drift and merge pain. The
 *   answer is to CONSUME it: thin wrappers that run the hardened SMARCH tools
 *   against this project's own registry/leases via SMA_ROOT. New capabilities in
 *   SMARCH reach every adopter for free, and nothing forks.
 * HOW: `sma adopt --target <dir>` writes `<dir>/sma` and `<dir>/spl` wrapper
 *   scripts (marked @sma-private-safe by being generic), a portfolio config
 *   scaffold, and the runtime dirs SPL/leases need. It never overwrites files
 *   that already exist unless --force.
 * @example
 *   npx github:B-EtterDigital/SMARCH adopt --target .
 *   ./sma spl doctor        # runs the hardened engine against your repo
 */
import { chmodSync, copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SMARCH_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');

interface AdoptOptions { target: string; force: boolean; json: boolean }

function parseArgs(argv: string[]): AdoptOptions {
  const out: AdoptOptions = { target: process.cwd(), force: false, json: false };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--target') { const v = argv[i + 1]; if (!v) throw new Error('--target needs a path'); out.target = resolve(v); i += 1; }
    else if (a === '--force') out.force = true;
    else if (a === '--json') out.json = true;
    else if (a === '--help' || a === '-h') { printHelp(); process.exit(0); }
    else throw new Error(`unknown argument: ${a}`);
  }
  return out;
}

function printHelp(): void {
  process.stdout.write(
    'Adopt the SMARCH engine into a project (consume, do not vendor).\n\n' +
    'Usage: sma adopt [--target <dir>] [--force] [--json]\n\n' +
    'Writes ./sma and ./spl wrappers that run the hardened SMARCH tools against\n' +
    'this project\'s own registry and leases via SMA_ROOT. Never overwrites\n' +
    'existing files unless --force.\n',
  );
}

function wrapper(tool: string): string {
  return [
    '#!/usr/bin/env bash',
    '# Generated by `sma adopt` — consume the hardened SMARCH engine against THIS',
    '# repo\'s data. SMARCH is the source of truth; this wrapper never drifts.',
    `SMARCH_DIR="\${SMARCH_DIR:-${SMARCH_DIR}}"`,
    'export SMA_ROOT="${SMA_ROOT:-$(cd "$(dirname "$0")" && pwd)}"',
    `exec node "$SMARCH_DIR/tools/${tool}" "$@"`,
    '',
  ].join('\n');
}

function writeIfAbsent(path: string, contents: string, force: boolean, created: string[], skipped: string[], mode?: number): void {
  if (existsSync(path) && !force) { skipped.push(path); return; }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  if (mode !== undefined) chmodSync(path, mode);
  created.push(path);
}

function main(): number {
  const opts = parseArgs(process.argv.slice(2));
  // A user adopting into a new location expects it created, not an error.
  if (!existsSync(opts.target)) mkdirSync(opts.target, { recursive: true });
  const created: string[] = [];
  const skipped: string[] = [];

  writeIfAbsent(resolve(opts.target, 'sma'), wrapper('sma.ts'), opts.force, created, skipped, 0o755);
  writeIfAbsent(resolve(opts.target, 'spl'), wrapper('sma-spl.ts'), opts.force, created, skipped, 0o755);
  writeIfAbsent(
    resolve(opts.target, 'registry/portfolio.config.json'),
    `${JSON.stringify({ priority_project_ids: [], overrides: {} }, null, 2)}\n`,
    opts.force, created, skipped,
  );
  for (const dir of ['.smarch/agent-context', 'registry']) mkdirSync(resolve(opts.target, dir), { recursive: true });

  // SPL needs its orphan-signature config; seed it from the engine's default so
  // `./spl doctor` works immediately after adoption.
  const splAgentsTarget = resolve(opts.target, 'registry/spl-agents.json');
  const splAgentsSource = resolve(SMARCH_DIR, 'registry/spl-agents.json');
  if ((!existsSync(splAgentsTarget) || opts.force) && existsSync(splAgentsSource)) {
    copyFileSync(splAgentsSource, splAgentsTarget);
    created.push(splAgentsTarget);
  }

  const result = { ok: true, target: opts.target, smarch_dir: SMARCH_DIR, created, skipped };
  if (opts.json) { process.stdout.write(`${JSON.stringify(result)}\n`); return 0; }
  process.stdout.write(`Adopted SMARCH into ${opts.target}\n`);
  for (const p of created) process.stdout.write(`  + ${p}\n`);
  for (const p of skipped) process.stdout.write(`  = ${p} (exists; --force to overwrite)\n`);
  process.stdout.write('\nNext: ./sma list  ·  ./sma spl doctor  ·  ./sma scan\n');
  return 0;
}

try {
  process.exit(main());
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`${JSON.stringify({ tool: 'sma-adopt', code: 'ADOPT_FAILED', message })}\n`);
  process.exit(1);
}
